# Generated by Django 5.0.6 on 2025-02-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_userprofile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=models.ImageField(default='files/basic/default.jpg', upload_to='files/pfps'),
        ),
    ]
