# Generated by Django 5.0.6 on 2025-02-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_userprofile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
