# Generated by Django 5.1.7 on 2025-04-02 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_event_eventuser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="user",
            new_name="creator",
        ),
        migrations.AddField(
            model_name="event",
            name="users",
            field=models.ManyToManyField(
                related_name="registered_users",
                through="app.EventUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="eventuser",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.event"
            ),
        ),
        migrations.AlterField(
            model_name="eventuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
