# Generated by Django 5.1.7 on 2025-04-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_rename_user_event_creator_event_users_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="achievements",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="education",
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="description",
            field=models.TextField(max_length=512, null=True),
        ),
    ]
